<a href="https://colab.research.google.com/github/md-rzn-alm/TMDB-Movies-Dateset/blob/main/tmdb_movieDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TMDB Movies Dataset 1923 to 2025 (upcoming included)

In [ ]:
import requests
import pandas as pd
import numpy as np

## **PAGE 1 DATA LOAD**

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1').json()

In [ ]:
popularity = []
vote_count = []
original_language =[]
title = []
vote_average = []
overview = []
release_date = []
original_title =[]
id = []
genre_ids = []

for i in response['results']:
      popularity.append(i['popularity'])
      vote_count.append(i['vote_count'])
      original_language.append(i['original_language'])
      title.append(i['title'])
      vote_average.append(i['vote_average'])
      overview.append(i['overview'])
      release_date.append(i['release_date'])
      original_title.append(i['original_title'])
      genre_ids.append(i['genre_ids'])
      id.append(i['id'])

d={'title':title ,"original_title" : original_title , 'id': id, 'genre_ids': genre_ids , 'vote_average' : vote_average , 'vote_count' : vote_count ,
   'original_language' : original_language , 'release_date' : release_date ,
   'popularity' : popularity , 'overview' : overview}
df = pd.DataFrame(d)
df

,title,original_title,id,genre_ids,vote_average,vote_count,original_language,release_date,popularity,overview
0,Mercy,Mercy,1236153,"[878, 28, 53]",7.094,506,en,2026-01-20,545.1617,"In the near future, a detective stands on tria..."
1,Shelter,Shelter,1290821,"[28, 80, 53]",7.021,97,en,2026-01-28,274.4696,A man living in self-imposed exile on a remote...
2,28 Years Later: The Bone Temple,28 Years Later: The Bone Temple,1272837,"[27, 53, 878]",7.184,619,en,2026-01-14,237.7059,Dr. Kelson finds himself in a shocking new rel...
3,The Orphans,Les Orphelins,1244975,[28],6.100,50,fr,2025-08-20,230.6038,"Gab and Driss, childhood friends on bad terms ..."
4,A Woman Scorned,A Woman Scorned,1301306,[28],6.300,10,en,2025-06-09,227.8739,Jas and her sister Laura are interrupted on th...
5,Hellfire,Hellfire,1088434,"[28, 53]",7.031,32,en,2026-02-05,217.9571,A drifter with a mysterious past arrives in a ...
6,Your Heart Will Be Broken,Твое сердце будет разбито,1523145,"[10749, 18]",0.000,0,ru,2026-03-26,186.6904,High school student Polina is saved from bully...
7,The Shadow's Edge,捕风追影,1419406,"[28, 80, 18, 53]",7.245,451,zh,2025-08-16,178.4926,Macau Police brings the tracking expert police...
8,Greenland 2: Migration,Greenland 2: Migration,840464,"[12, 53, 878]",6.510,509,en,2026-01-07,169.0134,Having found the safety of the Greenland bunke...
9,Zootopia 2,Zootopia 2,1084242,"[16, 35, 12, 10751, 9648]",7.608,1847,en,2025-11-26,168.5377,After cracking the biggest case in Zootopia's ...
10,Deathstalker,Deathstalker,1253000,"[14, 28, 12]",6.290,50,en,2025-10-10,158.6682,A powerful swordsman known as Deathstalker rec...
11,Space/Time,Space/Time,434853,"[878, 28, 53]",5.894,33,en,2025-05-01,146.0445,"After a fatal test shuts down their project, a..."
12,The Housemaid,The Housemaid,1368166,"[18, 9648, 53]",7.241,1303,en,2025-12-18,143.4842,"Trying to escape her past, Millie Calloway acc..."
13,The Wrecking Crew,The Wrecking Crew,1168190,"[28, 35, 80, 9648]",6.900,687,en,2026-01-28,131.0266,Estranged half-brothers Jonny and James reunit...
14,Cuerno Azulado,Cuerno Azulado,1634858,[28],7.778,9,es,2025-09-10,125.0657,
15,Predator: Badlands,Predator: Badlands,1242898,"[28, 878, 12]",7.718,2151,en,2025-11-05,122.1662,"Cast out from his clan, a young Predator finds..."
16,Avatar: Fire and Ash,Avatar: Fire and Ash,83533,"[878, 12, 14]",7.300,1819,en,2025-12-17,115.5859,In the wake of the devastating war against the...
17,"""Wuthering Heights""","""Wuthering Heights""",1316092,"[10749, 18]",6.505,377,en,2026-02-11,113.8131,Tragedy strikes when Heathcliff falls in love ...
18,War of the Worlds,War of the Worlds,755898,"[878, 53]",4.196,900,en,2025-07-29,108.9751,Will Radford is a top analyst for Homeland Sec...
19,The Dreadful,The Dreadful,1242937,[27],6.513,38,en,2026-02-20,99.7629,"In medieval England, Anne and her domineering ..."

**TOTAL 500 PAGES LOAD**

In [ ]:
final = pd.DataFrame()

for j in range(1,501):

  response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(j)).json()

  popularity = []
  vote_count = []
  language =[]
  title = []
  vote_average = []
  overview = []
  release_date = []
  genre_ids = []

  for i in response['results']:
      popularity.append(i['popularity'])
      vote_count.append(i['vote_count'])
      language.append(i['original_language'])
      title.append(i['title'])
      vote_average.append(i['vote_average'])
      overview.append(i['overview'])
      release_date.append(i['release_date'])
      genre_ids.append(i['genre_ids'])


  d={'title':title , 'genres_ids' : genre_ids, 'vote_average' : vote_average , 'vote_count' : vote_count ,'original_language' : language ,
     'release_date' : release_date ,'popularity' : popularity , 'overview' : overview}

  df = pd.DataFrame(d)

  final = pd.concat([df,final] , ignore_index=True)

final

,title,genres_ids,vote_average,vote_count,original_language,release_date,popularity,overview
0,Orphan: First Kill,"[27, 53]",6.600,2269,en,2022-07-27,2.7531,After escaping from an Estonian psychiatric fa...
1,New Female Prisoner Scorpion: Special Cellblock X,"[53, 18, 80]",5.100,5,ja,1977-06-18,2.7531,A nurse is framed for her involvement in the h...
2,Black Night,"[80, 18, 53]",6.971,17,tr,2023-04-28,2.7529,"Ishak, a wandering musician from a small mount..."
3,Albéniz,[18],0.000,0,es,1947-08-05,2.7529,"Isaac Albéniz was a child prodigy, and the vic..."
4,Slim,"[18, 10749]",6.300,3,en,1937-06-24,2.7529,Expert lineman Red takes Farm-boy Slim under h...
...,...,...,...,...,...,...,...,...
9994,Predator: Badlands,"[28, 878, 12]",7.718,2151,en,2025-11-05,122.1662,"Cast out from his clan, a young Predator finds..."
9995,Avatar: Fire and Ash,"[878, 12, 14]",7.300,1819,en,2025-12-17,115.5859,In the wake of the devastating war against the...
9996,"""Wuthering Heights""","[10749, 18]",6.505,377,en,2026-02-11,113.8131,Tragedy strikes when Heathcliff falls in love ...
9997,War of the Worlds,"[878, 53]",4.196,900,en,2025-07-29,108.9751,Will Radford is a top analyst for Homeland Sec...
9998,The Dreadful,[27],6.513,38,en,2026-02-20,99.7629,"In medieval England, Anne and her domineering ..."

In [ ]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              9999 non-null   object
 1   genres_ids         9999 non-null   object
 2   vote_average       9999 non-null   float64
 3   vote_count         9999 non-null   int64
 4   original_language  9999 non-null   object
 5   release_date       9999 non-null   object
 6   popularity         9999 non-null   float64
 7   overview           9999 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 625.1+ KB

In [ ]:
final.value_counts(['original_language'])

original_language
en                   6710
ja                    476
fr                    408
es                    294
de                    207
                     ...
nb                      1
sw                      1
st                      1
ve                      1
ur                      1
Name: count, Length: 69, dtype: int64

# Convert language code to original langauge name

In [ ]:
final['original_language'] = final['original_language'].replace('en' , 'english')
final['original_language'] = final['original_language'].replace('es' , 'Spanish')
final['original_language'] = final['original_language'].replace('it' , 'italian')
final['original_language'] = final['original_language'].replace('ko' , 'korean')
final['original_language'] = final['original_language'].replace('zh' , 'chinese')
final['original_language'] = final['original_language'].replace('de' , 'german')
final['original_language'] = final['original_language'].replace('te' , 'telugu')
final['original_language'] = final['original_language'].replace('za' , 'zhuang')
final['original_language'] = final['original_language'].replace('ja' , 'japanese')
final['original_language'] = final['original_language'].replace('cn' , 'chinese')
final['original_language'] = final['original_language'].replace('ar' , 'arabic')
final['original_language'] = final['original_language'].replace('hi' , 'hindi')
final['original_language'] = final['original_language'].replace('fr' , 'french')
final['original_language'] = final['original_language'].replace('ru' , 'russian')
final['original_language'] = final['original_language'].replace('ml' , 'malayalam')
final['original_language'] = final['original_language'].replace('th' , 'thai')
final['original_language'] = final['original_language'].replace('ta' , 'tamil')
final['original_language'] = final['original_language'].replace('te' , 'telugu')
final['original_language'] = final['original_language'].replace('tl' , 'tagalog')
final['original_language'] = final['original_language'].replace('bn' , 'bangali')
final['original_language'] = final['original_language'].replace('el' , 'greek')
final['original_language'] = final['original_language'].replace('pt' , 'Portuguese')
final['original_language'] = final['original_language'].replace('sv' , 'swedish')
final['original_language'] = final['original_language'].replace('he' , 'hebrew')
final['original_language'] = final['original_language'].replace('fa' , 'Persian')
final['original_language'] = final['original_language'].replace('cs' , 'czech')
final['original_language'] = final['original_language'].replace('kn' , 'kannada')
final['original_language'] = final['original_language'].replace('da' , 'danish')
final['original_language'] = final['original_language'].replace('tr' , 'turkish')
final['original_language'] = final['original_language'].replace('nl' , 'dutch')
final['original_language'] = final['original_language'].replace('id' , 'indonesian')
final['original_language'] = final['original_language'].replace('no' , 'norwegian')
final['original_language'] = final['original_language'].replace('pl' , 'polish')
final['original_language'] = final['original_language'].replace('fi' , 'finnish')
final['original_language'] = final['original_language'].replace('mk' , 'macedonish')
final['original_language'] = final['original_language'].replace('sk' , 'slovak')
final['original_language'] = final['original_language'].replace('sr' , 'serbian')
final['original_language'] = final['original_language'].replace('mr' , 'marathi')
final['original_language'] = final['original_language'].replace('hu' , 'hungarian')
final['original_language'] = final['original_language'].replace('uk' , 'ukrainian')
final['original_language'] = final['original_language'].replace('ro' , 'romanian')
final['original_language'] = final['original_language'].replace('sh' , 'Serbo-Croatian')
# will change rest language
# final['original_language'] = final['original_language'].replace('' , '')
# final['original_language'] = final['original_language'].replace('' , '')
# final['original_language'] = final['original_language'].replace('' , '')
# final['original_language'] = final['original_language'].replace('' , '')
# final['original_language'] = final['original_language'].replace('' , '')

In [ ]:
final.value_counts(['original_language'])

original_language
english              6710
japanese              476
french                408
Spanish               294
german                207
                     ...
macedonish              1
st                      1
sw                      1
ur                      1
ve                      1
Name: count, Length: 68, dtype: int64

#Convert genres_ids into genres

In [ ]:
def replace_elements(lst, mapping):
    """
    Replace elements in a list using a mapping dictionary.

    :param lst: list of elements
    :param mapping: dict {old_value: new_value}
    :return: new list with replaced values
    """
    return [mapping.get(x, x) for x in lst]

for i in final['genres_ids']:

  mapping = {
      28: "action", 12:'adventure' , 16 :'animation' , 35 :'comedy',80:'crime', 99:'documentry',18:'drama',10751:'family' ,14:'fantasy',
      36:'history',27:'horror',10402:'music',9648:'mystery',878:'science fiction',10770:'TV movie',53:'thriller',10752:'war',37:'western'
    }
  genres = replace_elements(i, mapping)
  print(genres)

['horror', 'thriller']
['thriller', 'drama', 'crime']
['crime', 'drama', 'thriller']
['drama']
['drama', 10749]
['comedy', 'drama']
['western', 'horror', 'drama']
['drama', 'fantasy', 'horror']
['animation']
['comedy', 'adventure']
['comedy']
['horror']
['drama']
['thriller']
['comedy', 'crime']
['horror', 'thriller', 'comedy', 'TV movie']
['comedy']
['drama']
['comedy', 10749]
['drama', 'comedy']
['drama']
[10749, 'comedy', 'drama', 'fantasy']
['drama']
['science fiction', 'horror']
['action', 'adventure', 'comedy']
['horror']
['drama']
['drama', 'history']
['comedy', 'drama']
['drama', 10749]
['comedy']
[10749, 'comedy']
['drama']
[]
[10749, 'comedy']
['comedy', 10749]
['horror']
['drama', 'thriller', 'mystery']
['TV movie', 'adventure', 'drama', 'thriller']
['drama']
['drama']
['fantasy', 'comedy', 'family']
['action', 'drama']
['thriller', 'action', 'adventure']
['comedy']
['comedy', 'action']
['comedy', 10749]
['drama', 'thriller', 'war']
['adventure', 'TV movie', 'drama']
['comedy']
['comedy', 'family', 'adventure']
['drama', 'thriller', 'crime', 'mystery']
['horror', 'fantasy']
['action', 'crime', 'science fiction', 'thriller']
['science fiction']
['science fiction', 'mystery', 'horror', 'thriller']
['science fiction', 'thriller']
['drama', 'history']
['crime']
['family', 'fantasy', 'science fiction', 'adventure', 'comedy']
['animation']
['action', 'adventure', 'comedy', 'family', 'fantasy', 'science fiction']
['action', 'thriller', 'fantasy', 'adventure']
['crime', 'drama']
['comedy', 'music']
['animation', 'drama', 10749, 'thriller', 'science fiction']
['comedy', 'thriller']
['drama', 'comedy', 10749]
[]
['horror']
['horror', 'mystery']
['comedy']
['horror']
['comedy', 10749, 'drama']
['thriller', 'horror', 10749, 'crime']
['TV movie', 'drama', 'history']
[10749]
['drama']
['drama', 'comedy']
['horror']
['horror', 'science fiction']
[]
['fantasy', 'mystery', 'thriller']
['horror', 'science fiction', 'mystery', 'thriller']
['drama']
['comedy']
[]
['drama', 'thriller', 'comedy', 'crime']
[10749, 'fantasy']
['fantasy', 'drama']
['action', 'animation', 'comedy']
['fantasy', 'family', 'adventure', 'TV movie']
['horror', 'crime', 'mystery']
['drama']
['action']
['action', 'thriller', 'crime']
['action', 'comedy', 'documentry']
['drama', 10749]
['drama', 'history', 'war']
[]
['comedy', 'drama']
['drama']
['documentry']
['comedy']
['horror']
['horror', 'thriller']
['drama', 10749, 'comedy']
['drama', 'thriller']
['drama', 10749]
['horror']
['comedy', 'drama']
['drama']
['comedy', 10749]
['drama', 'history']
['animation', 'family']
['action', 'thriller']
['horror', 'thriller']
['crime', 'drama', 10749, 'thriller']
['crime', 'drama', 'action', 'thriller']
['crime', 'action', 'drama']
['science fiction']
['action', 'crime']
['thriller', 'western', 'action', 'drama']
['action', 'crime', 'thriller', 'TV movie']
['drama']
['drama']
['comedy', 'drama']
['drama']
['horror', 'science fiction']
['horror']
['action', 'drama', 'thriller']
['thriller', 'crime', 10749, 'TV movie']
[10749, 'comedy']
['drama']
['comedy', 10749, 'TV movie']
['adventure', 'history', 'action']
['drama', 'comedy']
['thriller', 'action']
['drama', 'history']
['comedy', 'drama']
['comedy', 'drama']
['history', 'drama']
['action', 'thriller', 'crime', 'drama']
['crime']
['drama']
['drama']
['science fiction', 'horror']
['action', 'horror', 'mystery', 'science fiction', 'thriller']
['comedy', 10749]
['adventure', 'action', 'thriller']
['drama']
[10749]
['fantasy', 'family', 'TV movie']
['war', 'documentry']
['comedy', 'drama']
['drama']
['drama']
['drama', 'comedy']
['drama', 'family']
['drama', 'horror']
['drama']
[]
['drama', 'adventure']
['drama', 10749]
[10749, 'TV movie']
['drama', 10749]
['horror', 'mystery', 'science fiction', 'thriller']
['horror', 'drama', 'thriller', 'mystery']
['thriller', 'drama']
['science fiction', 'thriller']
['comedy']
['horror']
['horror']
['animation', 'family', 'TV movie', 'comedy', 'fantasy']
[10749]
[10749]
['crime', 'action']
['drama']
['drama', 'comedy']
['horror', 'mystery']
['TV movie', 'drama']
['mystery', 'thriller', 'horror', 'crime']
['adventure', 'comedy']
['family', 'comedy', 'animation']
['documentry']
[10749, 'comedy', 'drama']
['drama', 'comedy']
['horror', 'mystery', 'thriller']
['comedy']
['crime', 'thriller', 10749]
['thriller', 'mystery']
['mystery', 'drama', 10749]
['documentry']
['action', 'adventure', 'science fiction']
['family', 'animation']
['drama', 'mystery']
['drama', 'crime']
['adventure', 'drama', 'history']
['drama', 'action', 'crime', 'TV movie']
['drama', 'crime', 'thriller']
['comedy', 'documentry']
['drama']
['animation', 'adventure', 'family', 'comedy']
['drama']
['adventure', 'comedy', 'crime', 'thriller']
['comedy', 10749]
['thriller', 'action', 'comedy']
['comedy']
['crime', 'drama', 'thriller']
['drama', 'comedy']
['drama', 'comedy', 10749]
['drama', 'thriller', 'crime']
['animation', 'family', 'comedy']
[10749]
['comedy']
['animation', 'action', 'adventure', 'fantasy']
['drama']
['drama', 'action']
['comedy']
['science fiction', 'action', 'adventure', 'animation']
['drama', 'music']
['mystery']
['action', 'comedy', 'drama']
['drama']
['drama', 'crime', 'TV movie']
['comedy', 'drama', 10749]
[]
['action', 'science fiction', 'thriller']
['drama', 'comedy']
['horror', 'thriller']
['family', 'animation', 'comedy', 'adventure']
['comedy']
['documentry']
['drama', 'thriller']
['horror']
['science fiction']
['comedy', 'drama']
['mystery', 'crime', 'drama', 'thriller']
['drama', 'thriller']
['comedy', 'drama']
['comedy', 10749, 'drama']
['action', 'crime']
['science fiction', 'action', 'thriller']
['comedy', 'thriller', 'crime']
['crime', 'drama', 'thriller']
['animation', 'TV movie', 'action', 'comedy', 'crime']
['comedy', 'family', 'science fiction']
['thriller', 'drama', 'crime']
['western']
[10749, 'comedy']
['crime', 'drama', 10749]
['comedy', 'drama', 'horror', 'thriller']
['drama', 'mystery']
['fantasy', 'comedy']
[]
['drama']
['thriller', 'horror']
['thriller', 'mystery']
['documentry']
['comedy']
['action', 'TV movie']
[10749, 'drama']
['drama', 'TV movie', 'comedy']
['drama', 'history']
['thriller']
['drama', 'comedy', 'music']
['thriller', 'science fiction', 'action']
['drama']
['comedy', 'science fiction', 'horror']
['comedy']
['fantasy', 'drama', 'mystery']
['drama']
['adventure', 'comedy', 'fantasy', 'action', 'family']
['horror', 'fantasy']
['drama', 10749, 'history']
['action', 'drama', 'thriller']
['drama']
['drama']
['drama']
['action', 'adventure', 'fantasy']
['comedy', 'horror']
['action', 'thriller']
['horror', 'thriller', 'fantasy', 'comedy']
['documentry']
['science fiction', 'drama', 'TV movie']
['drama']
['thriller', 'horror']
['animation', 'drama', 'fantasy', 10749]
['action', 'thriller']
['fantasy', 'comedy']
['horror', 'thriller']
['drama']
[]
['drama', 'comedy']
['animation', 'adventure', 'comedy']
['drama']
['history', 'war', 10749]
[]
['action', 'thriller', 'TV movie']
['action', 'drama', 'history']
['science fiction', 'mystery', 'thriller', 10749]
['comedy', 'drama']
['history', 'drama', 10749]
['drama', 'thriller', 10749]
['documentry']
[10749, 'comedy', 'family']
['documentry']
[]
[]
['documentry']
['adventure', 'action', 'animation', 'comedy', 'science fiction', 'fantasy']
['drama', 'thriller']
['fantasy', 'horror']
['drama']
['drama']
['comedy', 'drama']
['drama']
['drama', 10749]
[10749, 'thriller']
[]
['horror', 'mystery', 'thriller']
['drama']
['comedy']
['horror']
['action', 'crime', 'thriller']
['action', 'adventure']
['science fiction', 'action', 'thriller', 'horror']
['horror', 'thriller']
['family', 'science fiction']
['thriller']
['adventure', 'drama']
['drama', 'comedy']
['action', 'thriller', 'crime']
['comedy']
['comedy']
[]
['comedy']
['drama']
['horror', 'comedy']
['music', 'drama']
['thriller', 'mystery', 10749, 'horror']
['drama']
['drama', 10749]
['comedy']
['science fiction', 'thriller', 'mystery']
['drama', 10749, 'science fiction', 'adventure']
['drama', 10749]
[]
['western', 'TV movie']
['drama']
['drama', 'comedy']
['comedy', 'TV movie']
['comedy', 'drama', 'TV movie']
['documentry']
[10749, 'comedy']
['horror', 'thriller']
['thriller', 'fantasy', 'action', 'comedy']
['animation', 'horror', 'drama']
['thriller']
['horror']
['horror']
['horror', 'thriller']
['documentry']
['animation', 'adventure', 'comedy', 'science fiction', 'drama', 'family', 'fantasy']
['drama']
['comedy', 'music', 10749]
['comedy']
['comedy', 'drama', 'music']
['crime', 'drama', 10749]
['comedy', 'drama']
[]
['drama']
['thriller', 'action']
['comedy', 'music']
['drama']
['drama']
['drama']
['drama']
['horror', 'thriller', 'mystery']
['animation', 'comedy']
['action', 'drama', 'thriller', 'adventure']
['adventure', 'fantasy']
['crime', 'thriller', 'comedy']
['documentry']
[]
['comedy']
['comedy']
['family', 'adventure', 'animation', 'fantasy', 'science fiction']
['drama']
['science fiction', 'thriller']
['comedy']
['comedy', 'action', 'family']
['science fiction', 10749, 'action']
['comedy', 'horror']
['horror', 'thriller']
['documentry']
['action', 'crime', 'drama', 'TV movie']
['drama', 'history', 10749]
['drama']
['drama', 10749]
['science fiction', 'animation', 'adventure']
['drama']
[]
['science fiction', 'thriller', 'horror']
['drama']
['thriller', 'action', 'science fiction']
['science fiction', 'horror', 'thriller', 'drama']
[]
['drama', 'comedy', 10749]
['drama', 'mystery', 'thriller']
['action', 'science fiction']
['comedy', 'drama']
['action', 'crime', 'thriller']
['comedy', 'fantasy']
['crime', 'thriller', 'drama']
['drama']
['horror', 'thriller', 'drama', 'mystery']
['drama', 'action', 'crime']
['comedy']
['drama']
['comedy']
['comedy', 'action', 10749]
['drama', 'family']
['comedy', 'drama', 10749]
['drama', 10749, 'history']
['comedy']
['family', 'adventure', 'comedy']
['crime', 'drama', 'history']
[]
['drama', 'comedy', 10749]
['music', 'comedy', 10749]
['drama', 'thriller']
['drama']
['comedy']
['drama']
['documentry']
['action']
['horror', 'thriller']
['music', 'comedy']
['documentry']
['comedy', 'family', 'animation', 'adventure']
['drama']
['drama', 'horror']
['action', 'adventure', 'fantasy', 'comedy', 10749]
['family', 'animation']
['western', 'drama', 10749]
[]
['fantasy', 'adventure', 'comedy', 'TV movie']
['crime', 'comedy']
['science fiction', 'action', 'thriller', 'mystery']
['comedy', 'history']
['drama', 10749]
['comedy', 'music', 10749]
['horror']
['drama', 'action', 'TV movie']
['drama']
['horror', 'drama', 'fantasy']
['horror', 'thriller']
['comedy', 'family', 'TV movie']
['science fiction', 'thriller', 'drama']
['drama']
['action', 'thriller']
['western', 'war']
['comedy', 'drama', 10749]
['action', 'comedy', 'drama', 10749]
['documentry']
['drama', 'comedy']
['comedy']
['comedy', 'drama', 10749]
['family', 'adventure']
['drama']
['horror', 'comedy']
[]
['crime', 'drama', 'thriller']
['thriller', 'crime', 'action']
[]
['action', 'thriller', 'crime', 'comedy']
['adventure', 'animation', 'comedy', 'family']
['drama', 'horror']
['drama', 10749]
['animation', 'science fiction', 'action', 'adventure', 'family']
['thriller', 'drama']
[10749, 'comedy']
['comedy']
['family', 'animation']
['horror', 'mystery']
['comedy']
['crime', 'drama', 'thriller']
['comedy', 'drama']
[10749, 'comedy']
['documentry']
['fantasy', 'action', 'drama']
[10749, 'fantasy', 'TV movie']
['action', 'adventure', 'drama']
['action', 'drama', 'war']
['comedy', 'action', 'fantasy']
[10749, 'comedy', 'drama']
['adventure', 'action', 'fantasy', 'science fiction', 'thriller', 10749, 'animation']
['adventure', 'comedy', 'family', 'fantasy', 'science fiction']
['fantasy', 'adventure', 'comedy']
['comedy', 'crime', 10749]
['drama', 'crime', 'thriller', 'history']
['music', 10749, 'drama']
['horror', 'thriller', 'action']
['comedy', 'drama']
['history', 'action', 'war']
['drama']
['adventure', 'science fiction', 'action']
['drama']
['horror', 'science fiction', 'thriller']
['comedy']
[10749, 'comedy']
['crime', 'drama', 'thriller']
['crime', 'thriller', 'horror']
['comedy', 'fantasy', 'adventure']
['comedy', 'crime', 10749]
[]
['drama', 10749]
['drama', 'mystery', 'thriller']
['horror', 'action', 'thriller']
['action']
['crime', 'drama']
['comedy']
['drama', 'thriller']
['drama', 'thriller', 'crime']
['drama', 'comedy']
['comedy']
['drama']
['horror', 'action', 'thriller']
['drama', 10749]
['comedy', 'drama']
[10749, 'comedy']
['comedy', 'drama']
['comedy', 'science fiction']
[10749, 'action', 'family']
['action', 'drama']
['drama', 10749]
[]
['drama', 'action', 'thriller']
['action', 'comedy', 'crime', 10749]
['drama', 'TV movie']
['crime', 'drama']
[10749, 'comedy']
[]
['drama']
['comedy', 'fantasy', 'horror']
[10749, 'comedy', 'drama']
['drama', 'thriller']
['comedy', 'horror', 'TV movie']
['horror']
['drama', 'TV movie']
['drama', 10749]
['documentry']
['crime']
['horror', 'thriller']
['comedy']
['fantasy', 'comedy', 10749]
['drama', 'thriller', 'action', 'TV movie']
['comedy']
['action']
['drama', 'science fiction', 'mystery']
['adventure', 'drama']
[]
['adventure', 'horror', 'mystery']
['drama', 'thriller', 'mystery', 'war']
['action', 'crime', 'thriller']
['comedy']
['animation', 'TV movie']
['drama', 10749]
['crime', 'drama', 'thriller']
['drama', 'music', 10749]
['comedy', 'TV movie']
['comedy']
[10749, 'comedy']
['drama', 10749]
['horror', 'thriller']
['comedy']
['mystery']
['drama', 'horror', 'science fiction']
['comedy']
['comedy']
['horror']
['drama', 10749]
['drama', 'history', 'TV movie']
['mystery']
['adventure', 'history']
['horror', 'drama']
['drama']
['documentry']
['animation', 'adventure', 'family', 'fantasy', 'science fiction']
['western']
['comedy']
['action', 'thriller', 'drama', 'fantasy']
['drama', 'horror', 'mystery', 'TV movie']
['horror']
['comedy', 10749]
['comedy', 'music', 'science fiction', 'fantasy']
['comedy', 'crime']
['science fiction', 10749]
['action', 'comedy', 10749]
['drama']
['action', 'drama', 'thriller', 'crime', 'mystery']
['comedy', 10749, 'science fiction', 'mystery']
['comedy']
['fantasy', 'drama']
['science fiction']
['animation', 'adventure', 'family', 'fantasy', 'science fiction']
['horror', 'science fiction', 'thriller', 'action', 'TV movie']
['drama']
['drama', 'crime']
['comedy', 'drama']
['drama']
['family', 'fantasy']
['documentry']
['horror', 'thriller']
['comedy']
['drama', 'comedy', 'fantasy', 'science fiction']
['science fiction', 'comedy', 'adventure', 10749]
[10749, 'comedy']
['drama', 'comedy', 'fantasy']
[]
[10749, 'comedy', 'action']
['comedy', 'drama', 'family']
['drama', 'comedy', 10749]
['animation', 'science fiction', 'thriller']
['adventure']
['action', 10749]
['comedy']
['action', 'adventure', 'comedy', 'crime', 'thriller']
['comedy', 'music']
[]
['comedy', 'action', 'thriller']
['comedy', 'drama']
['comedy']
['animation', 'family', 'adventure', 'comedy']
['family', 'adventure', 'comedy', 'fantasy', 'action']
['action', 'crime', 'drama', 'mystery', 'thriller']
[10749]
['drama']
['fantasy', 'horror', 'thriller']
['comedy']
['drama']
['war', 'drama', 'history']
['comedy', 'drama', 'family']
['crime', 'drama']
['action', 'science fiction', 'horror']
[10749, 'fantasy']
['horror']
['comedy', 'drama', 10749]
['comedy', 'war']
['drama', 'crime']
['action']
['crime', 'drama']
['drama', 10749]
['comedy', 'horror']
[]
['horror']
['action', 'comedy', 'science fiction', 'fantasy']
['drama']
['comedy', 10749, 'drama']
['history', 'drama']
['horror', 'comedy', 'mystery']
['science fiction', 'animation', 'fantasy']
['comedy']
['comedy']
[10749]
['documentry']
['comedy']
['drama']
['drama']
['comedy']
['drama', 'war', 'action']
['drama']
['crime', 'drama', 'thriller']
['comedy', 'family']
['comedy', 'fantasy']
[]
['horror', 'action', 'science fiction']
['comedy']
['drama']
['horror', 'thriller', 'science fiction']
['comedy', 'science fiction']
['comedy']
['comedy']
['comedy', 10749]
['drama']
['horror', 'thriller', 'mystery']
['drama', 'horror', 'thriller']
['drama', 'comedy', 'music']
['drama']
['comedy', 10749]
['animation', 'comedy', 'adventure', 'fantasy']
[10749, 'comedy', 'drama']
['fantasy', 'horror']
['family', 'adventure', 'fantasy']
[]
['thriller', 'drama', 'adventure', 'action', 'history']
['drama']
['comedy', 10749]
['action', 'drama']
['action', 'thriller']
['drama']
['action', 'comedy', 'crime']
['drama']
['action', 'animation']
[10749, 'war', 'drama']
['drama', 'action', 10749]
['drama']
['comedy', 'horror', 'science fiction']
['comedy']
['horror', 'thriller', 10749]
['drama', 'history']
['thriller', 'action']
['drama', 'thriller']
['comedy']
['science fiction', 'thriller']
['drama', 'history', 10749]
['horror', 'science fiction']
['drama', 10749]
['drama']
['horror']
['drama']
['drama', 'mystery', 10749]
['music']
['comedy', 'family', 'adventure', 'fantasy']
['comedy']
['drama', 10749]
[10749, 'comedy']
['comedy', 10749]
['horror']
['animation', 'family']
['documentry', 'music']
['comedy']
['documentry']
['comedy']
['comedy']
['drama', 'war', 10749]
[]
['thriller', 'crime']
['action', 'comedy', 'horror', 'thriller']
['action']
['comedy']
['drama']
['drama']
['drama']
['drama']
[10749, 'TV movie']
['drama']
['drama']
['family', 'adventure', 'drama']
['comedy']
['comedy']
['drama']
[10749, 'drama', 'comedy']
['comedy', 'drama', 10749]
['horror', 'thriller', 'mystery']
[10749, 'drama']
['drama', 10749]
['drama']
['drama', 'comedy']
['comedy', 10749, 'drama']
['comedy']
['comedy', 'family']
['comedy', 'fantasy', 'drama']
['drama', 10749]
['drama']
[10749, 'fantasy', 'drama']
['comedy', 'drama', 10749, 'crime']
['thriller', 'drama']
['action', 'comedy', 'adventure', 'crime']
['drama', 10749, 'thriller']
['action', 'thriller']
['drama', 10749]
['comedy', 'drama']
['fantasy', 'horror', 10749]
['comedy', 'family']
['music', 'drama']
['comedy']
['drama']
['action', 'drama', 'mystery', 'thriller']
[10749, 'drama', 'family', 'music', 'TV movie']
['drama', 'history', 'war']
['music']
[10749, 'comedy']
['drama', 10749]
['documentry', 'comedy']
['drama']
['comedy', 'science fiction', 'TV movie']
['comedy']
['animation', 'comedy']
['comedy']
['family', 'adventure', 'fantasy', 'comedy']
['horror', 'comedy']
['family', 'drama']
[]
[]
['drama']
['animation', 'science fiction', 'action']
['drama', 'history', 'war']
['science fiction', 'action', 'adventure']
['drama']
['family', 'comedy', 'adventure', 'animation']
['drama']
['comedy', 'drama', 10749]
['drama', 'mystery', 'crime']
['thriller', 'drama', 'crime']
[]
['action', 'adventure', 'crime', 'thriller']
['war', 'drama', 'adventure']
['thriller', 'horror']
['drama']
[10749, 'comedy', 'TV movie']
['drama', 10749]
['horror']
['fantasy', 'horror']
['music', 'documentry']
['drama', 'thriller']
['comedy', 'crime']
['comedy']
['comedy']
['comedy', 'science fiction']
[]
['comedy', 'drama']
['adventure', 'comedy', 'animation', 'family']
['drama']
['drama']
['drama']
['horror']
['history', 'crime', 'thriller']
[10749, 'comedy', 'drama']
['drama', 'thriller', 'mystery']
['thriller', 'mystery']
['fantasy', 'comedy', 10749, 'TV movie']
['thriller', 'drama']
['adventure', 'fantasy', 10749]
['documentry']
['crime', 'drama']
['comedy']
['TV movie', 'adventure', 'animation', 'fantasy', 'music', 'science fiction', 'action', 'drama']
['drama']
['horror', 'thriller']
['thriller']
['action', 'comedy', 'crime']
['animation', 'comedy', 'drama', 'family']
['action', 'adventure', 'drama']
['drama', 'horror', 'mystery', 'science fiction', 'thriller']
['action', 'horror', 'thriller']
['action', 'comedy', 'crime', 'thriller']
['comedy', 10749]
['comedy', 'drama']
['thriller', 'science fiction']
['thriller', 'crime', 'drama']
['thriller', 'crime', 'TV movie']
['animation', 'family']
['science fiction', 'action', 'crime', 'animation', 'drama']
['drama', 'mystery']
['science fiction', 'thriller']
['horror', 'science fiction', 'comedy']
['action', 'crime']
['comedy', 'drama', 10749]
['comedy', 10749]
['drama', 'TV movie']
['science fiction']
['drama']
['horror']
['action', 'comedy']
['drama']

In [ ]:
final

,title,genres_ids,vote_average,vote_count,original_language,release_date,popularity,overview,genres
0,Orphan: First Kill,"[27, 53]",6.600,2269,english,2022-07-27,2.7531,After escaping from an Estonian psychiatric fa...,"[horror, thriller]"
1,New Female Prisoner Scorpion: Special Cellblock X,"[53, 18, 80]",5.100,5,japanese,1977-06-18,2.7531,A nurse is framed for her involvement in the h...,"[thriller, drama, crime]"
2,Black Night,"[80, 18, 53]",6.971,17,turkish,2023-04-28,2.7529,"Ishak, a wandering musician from a small mount...","[crime, drama, thriller]"
3,Albéniz,[18],0.000,0,Spanish,1947-08-05,2.7529,"Isaac Albéniz was a child prodigy, and the vic...",[drama]
4,Slim,"[18, 10749]",6.300,3,english,1937-06-24,2.7529,Expert lineman Red takes Farm-boy Slim under h...,"[drama, 10749]"
...,...,...,...,...,...,...,...,...,...
9994,Predator: Badlands,"[28, 878, 12]",7.718,2151,english,2025-11-05,122.1662,"Cast out from his clan, a young Predator finds...","[action, science fiction, adventure]"
9995,Avatar: Fire and Ash,"[878, 12, 14]",7.300,1819,english,2025-12-17,115.5859,In the wake of the devastating war against the...,"[science fiction, adventure, fantasy]"
9996,"""Wuthering Heights""","[10749, 18]",6.505,377,english,2026-02-11,113.8131,Tragedy strikes when Heathcliff falls in love ...,"[10749, drama]"
9997,War of the Worlds,"[878, 53]",4.196,900,english,2025-07-29,108.9751,Will Radford is a top analyst for Homeland Sec...,"[science fiction, thriller]"
9998,The Dreadful,[27],6.513,38,english,2026-02-20,99.7629,"In medieval England, Anne and her domineering ...",[horror]

Re-arranging the column positions

In [ ]:
final = final[
    ['title', 'genres_ids', 'genres', 'vote_average', 'vote_count',
     'original_language', 'release_date', 'popularity', 'overview']
]

In [ ]:
final

,title,genres_ids,genres,vote_average,vote_count,original_language,release_date,popularity,overview
0,Orphan: First Kill,"[27, 53]","[horror, thriller]",6.600,2269,english,2022-07-27,2.7531,After escaping from an Estonian psychiatric fa...
1,New Female Prisoner Scorpion: Special Cellblock X,"[53, 18, 80]","[thriller, drama, crime]",5.100,5,japanese,1977-06-18,2.7531,A nurse is framed for her involvement in the h...
2,Black Night,"[80, 18, 53]","[crime, drama, thriller]",6.971,17,turkish,2023-04-28,2.7529,"Ishak, a wandering musician from a small mount..."
3,Albéniz,[18],[drama],0.000,0,Spanish,1947-08-05,2.7529,"Isaac Albéniz was a child prodigy, and the vic..."
4,Slim,"[18, 10749]","[drama, 10749]",6.300,3,english,1937-06-24,2.7529,Expert lineman Red takes Farm-boy Slim under h...
...,...,...,...,...,...,...,...,...,...
9994,Predator: Badlands,"[28, 878, 12]","[action, science fiction, adventure]",7.718,2151,english,2025-11-05,122.1662,"Cast out from his clan, a young Predator finds..."
9995,Avatar: Fire and Ash,"[878, 12, 14]","[science fiction, adventure, fantasy]",7.300,1819,english,2025-12-17,115.5859,In the wake of the devastating war against the...
9996,"""Wuthering Heights""","[10749, 18]","[10749, drama]",6.505,377,english,2026-02-11,113.8131,Tragedy strikes when Heathcliff falls in love ...
9997,War of the Worlds,"[878, 53]","[science fiction, thriller]",4.196,900,english,2025-07-29,108.9751,Will Radford is a top analyst for Homeland Sec...
9998,The Dreadful,[27],[horror],6.513,38,english,2026-02-20,99.7629,"In medieval England, Anne and her domineering ..."

In [ ]:
final.to_csv("tmdbMovies_dataset.csv", index=False, header=True)

In [ ]:
final.to_excel("tmdbMovies_dataset.xlsx", index=False, header=True)

In [ ]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              9999 non-null   object
 1   genres_ids         9999 non-null   object
 2   genres             9999 non-null   object
 3   vote_average       9999 non-null   float64
 4   vote_count         9999 non-null   int64
 5   original_language  9999 non-null   object
 6   release_date       9999 non-null   object
 7   popularity         9999 non-null   float64
 8   overview           9999 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 703.2+ KB

# Change the datatype of the columns

In [ ]:
final = final.astype({
    'vote_average': float,
    'vote_count': int,
    'popularity': float
})

In [ ]:
import datetime

In [ ]:
final['release_date'] = pd.to_datetime(final['release_date'], errors='coerce')

In [ ]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              9999 non-null   object
 1   genres_ids         9999 non-null   object
 2   genres             9999 non-null   object
 3   vote_average       9999 non-null   float64
 4   vote_count         9999 non-null   int64
 5   original_language  9999 non-null   object
 6   release_date       9937 non-null   datetime64[ns]
 7   popularity         9999 non-null   float64
 8   overview           9999 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 703.2+ KB

In [ ]:
final

,title,genres_ids,genres,vote_average,vote_count,original_language,release_date,popularity,overview
0,Orphan: First Kill,"[27, 53]","[horror, thriller]",6.600,2269,english,2022-07-27,2.7531,After escaping from an Estonian psychiatric fa...
1,New Female Prisoner Scorpion: Special Cellblock X,"[53, 18, 80]","[thriller, drama, crime]",5.100,5,japanese,1977-06-18,2.7531,A nurse is framed for her involvement in the h...
2,Black Night,"[80, 18, 53]","[crime, drama, thriller]",6.971,17,turkish,2023-04-28,2.7529,"Ishak, a wandering musician from a small mount..."
3,Albéniz,[18],[drama],0.000,0,Spanish,1947-08-05,2.7529,"Isaac Albéniz was a child prodigy, and the vic..."
4,Slim,"[18, 10749]","[drama, 10749]",6.300,3,english,1937-06-24,2.7529,Expert lineman Red takes Farm-boy Slim under h...
...,...,...,...,...,...,...,...,...,...
9994,Predator: Badlands,"[28, 878, 12]","[action, science fiction, adventure]",7.718,2151,english,2025-11-05,122.1662,"Cast out from his clan, a young Predator finds..."
9995,Avatar: Fire and Ash,"[878, 12, 14]","[science fiction, adventure, fantasy]",7.300,1819,english,2025-12-17,115.5859,In the wake of the devastating war against the...
9996,"""Wuthering Heights""","[10749, 18]","[10749, drama]",6.505,377,english,2026-02-11,113.8131,Tragedy strikes when Heathcliff falls in love ...
9997,War of the Worlds,"[878, 53]","[science fiction, thriller]",4.196,900,english,2025-07-29,108.9751,Will Radford is a top analyst for Homeland Sec...
9998,The Dreadful,[27],[horror],6.513,38,english,2026-02-20,99.7629,"In medieval England, Anne and her domineering ..."

In [ ]:
final = final.sort_values(by='release_date', ascending=False)

In [ ]:
final.tail(100)

,title,genres_ids,genres,vote_average,vote_count,original_language,release_date,popularity,overview
5616,Athleten,[],[],0.000,0,german,1925-03-18,3.8323,
2166,Greed,"[18, 80]","[drama, crime]",7.314,196,english,1924-12-04,3.0401,"When housewife Trina wins the lottery, her com..."
5011,Her Man,"[35, 18, 10749]","[comedy, drama, 10749]",0.000,0,english,1924-02-10,3.6350,Silent Western about a gal fighting the elemen...
2625,Roulette,[18],[drama],0.000,0,english,1924-01-19,3.1203,"Before he can avenge a crooked card game, Dan ..."
753,Zaza,"[10749, 18, 35]","[10749, drama, comedy]",6.188,24,english,1923-10-21,2.8396,Zaza is an actress and the favorite at an open...
...,...,...,...,...,...,...,...,...,...
9011,Luny Tunes: Más Flow 2,[10402],[music],0.000,0,english,NaT,8.3065,"In this music sampler, Francisco Saldana and V..."
9087,AiScReam presents TOPPING LIVE Tokechau Maeni ...,[],[],0.000,0,japanese,NaT,8.7330,"Live event hosted by AiScReam, a special Unit ..."
9571,Maintenance,[],[],3.000,1,english,NaT,14.4441,Maintenance is filmmaker Adele Horne’s explora...
9583,The Forgotten War: Hollywood's Vietnam in the ...,[99],[documentary],0.000,0,english,NaT,9.3982,"Produced and filmed in 2019, but finally relea..."
9761,The Industry,[],[],0.000,0,english,NaT,17.4351,Starring some of the biggest stars in the ente...

In [ ]:
final.to_csv("tmdbMovies_dataset1.csv", index=False, header=True)

In [ ]:
final.to_excel("tmdbMovies_dataset1.xlsx", index=False, header=True)